### ISSUE TITLE
gatsby-theme-carbon v3.0.0

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#1252]
A new major version for this theme is in progress. The work to update this theme to use Gatsby v4 and also to use Carbon v11 merged into one. Currently the Carbon website (v11) is using a build of the theme published on `next` that has already incorporated both Gatsby v4 and Carbon v11. It's working and we'd like to release this as a formal new major version but a few things are lingering and need to be finished.

**Checklist**

- [x] Gatsby theme v3: Migrate the example site to use v3
- [x] Gatsby theme v3: Document the migration path
  - [x] Record steps taken to update the example site
  - [x] Record the steps taken to update the Carbon website
  - [x] Document and publish relevant steps on the example website and in the repository
- [x] Gatsby theme v3: Vet the migration path by migrating an ancillary site (IDL?, Design career playbook?)
  - [x] Much of the same content from the v2 migration guide carries over
  - [x] v11 migration steps - swap out tokens, etc. point to the v11 migration guide
    - "Your mileage may vary based on the complexity of your site"
- [x] Gatsby theme v3: Publish! 🎉 
  - [x] Publish to npm
  - [x] Announce - slack, medium blogpost?
- [ ] Support
  - Go to development office hours
  - This is effectively another v11 migration
  -

**Comment by kubijo** [comment]
Do you guys plan to, as part of this initiative, also update to latest `gatsby-plugin-mdx` (and other transitive packages) [to support MDX2](https://www.gatsbyjs.com/docs/reference/release-notes/v4.21/#gatsby-plugin-mdx-v4) and to using and to using [gatsby-head](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head) instead of currently used helmet?

I just had a shot at overloading you with the former, but it would be such an involved change that it would not make sense…

**Comment by tay1orjones** [comment]
[v3.0.0](https://github.com/carbon-design-system/gatsby-theme-carbon/releases/tag/v3.0.0) is now published

**Comment by tay1orjones** [comment]
@kubijo The full list of what was updated can be found in the [changelog](https://github.com/carbon-design-system/gatsby-theme-carbon/releases/tag/v3.0.0), specifically the [changelog diff](https://github.com/carbon-design-system/gatsby-theme-carbon/compare/v2.3.2...v3.0.0#diff-196c84e978b4eff53eda0e59684ee7bd796e6a3e25a634d0d8115fc4e640e726)

**Comment by kubijo** [comment]
I can see that and thanks to all involved for the undertaking & documentation... but it doesn't answer the questions I have raised-
