### ISSUE TITLE
Gatsby v5 ☂️

### ISSUE THREAD

**Issue by eng618** [carbon-design-system/gatsby-theme-carbon#1324]
### Summary

Upgrade the theme to use Gatsby v5

### Justification

Keeping up with technology changes, and security compliance.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1425
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1426
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1427
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1428
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1439
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1440
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1449
- [ ] https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1429
```

**Comment by eng618** [comment]
Most of this work is done on the `next` branch. 

The remaining peaces are as follows:

- [ ] Update layouts to support the [upgraded mdx](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#layouts)

**Comment by eng618** [comment]
For a little more context. The `defaultLayouts` node for the **gatsby-plugin-mdx** plugin is no longer a valid configuration. So, the below templates for **Default.js** and **Homepage.js** need to be converted into components that can be injected into every page. There are a few ways to do this, as outlined in the linked docs above.

```js
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    extensions: mdxExtensions,
    gatsbyRemarkPlugins: [
      ...defaultRemarkPlugins,
      ...gatsbyRemarkPlugins,
    ],
    remarkPlugins,
    defaultLayouts: {
      default: require.resolve('./src/templates/Default.js'),
      home: require.resolve('./src/templates/Homepage.js'),
      ...extraLayouts,
    },
  },
},
```

**Comment by muditjuneja** [comment]
More observed issues in next - 

- [ ] Tables listing the component props is not being rendered correctly
- [ ] Code blocks having more than 8 lines are not being rendered correctly 

<img width="1014" alt="Screenshot 2024-02-08 at 2 06 16 AM" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/15162221/4da01b80-5006-4bf6-b75f-cb77f72bd155">
<img width="1287" alt="Screenshot 2024-02-08 at 2 06 32 AM" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/15162221/15c3da9b-16ad-4c52-9e77-041aff2b61cc">

**Comment by alisonjoseph** [comment]
@eng618 was looking at the webpack warnings and I think it _may_ be something we can ignore. https://robertmarshall.dev/blog/fix-warn-chunk-commons-mini-css-extract-plugin-error-in-gatsby-js/
