### ISSUE TITLE
Website June Iteration plan

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#148]
# June Iteration Plan

This plan captures our work on the website project for **June**. 

### Dev
@alisonjoseph 
@vpicone 
@lovemecomputer (half-time)
@dakahn (half-time)
Abbey (17th)

### Design
@jeanservaas 
@designertyler 

## Endgame

**July 8th, 2019**: Code freeze for the endgame
**July 12th, 2019**: Endgame done 

The endgame details for this iteration are tracked in the [Website project](https://github.com/orgs/carbon-design-system/projects/10)

## Website

Our **primary goals** are to update the IBM Design Language website to use our Gatsby theme. Continue support, fixes, and documentation for the Carbon Gatsby theme. Update documentation on the Carbon website, along with updating designs for component status page, component variant switcher and an updated IA plan for Carbon add-on sites.

#### Design
- [ ] design the IA of going between carbon site & add-on sites https://github.com/carbon-design-system/gatsby-theme-carbon/issues/159
- [ ] component status page https://github.com/carbon-design-system/carbon-website/issues/1486
- [ ] deprecate experimental section in favor or inline meta data? https://github.com/carbon-design-system/gatsby-theme-carbon/issues/158

#### Content
- [ ] component usage tab, aka templatizing usage page content
- [ ] redesign theme page (proj: theme)
- [ ] guideline for contributing to website (proj: contribution)
- [ ] README of Code tab

#### Dev
- [x] Gatsby theme - nav bugs https://github.com/carbon-design-system/gatsby-theme-carbon/issues/33
- [x] Gatsby theme - feature card responsive image enhancements https://github.com/carbon-design-system/gatsby-theme-carbon/issues/116
- [x] Convert IDL content to MDX https://github.com/carbon-design-system/design-language-website/issues/3
- [ ] Gatsby theme docs/blog post
- [ ] Reduce Netlify build time for Carbon website

Our **stretch goalsl** are

- [ ] Convert Carbon website to use our Gatsby theme
- [ ] IBM approved analytics solution for websites

---

#### Content
- [ ] Determine "core four" H2s https://github.com/carbon-design-system/carbon-website/issues/1599
- [ ] Establish page pattern w/ Sketch spec https://github.com/carbon-design-system/carbon-website/issues/1600
- [ ] Bring all existing content within new page pattern https://github.com/carbon-design-system/carbon-website/issues/1602
- [ ] Lead art on usage pages https://github.com/carbon-design-system/carbon-website/issues/1603
- [ ] Create and flesh out missing content https://github.com/carbon-design-system/carbon-website/issues/1604
- [ ] Replace variant images with contextual images https://github.com/carbon-design-system/carbon-website/issues/1605
