### ISSUE TITLE
Nav divider is wrong color in dark theme

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1507]
![Screenshot 2024-09-05 at 7 36 53 AM](https://github.com/user-attachments/assets/12ef3cc4-6a76-4968-997a-65f3f5248c22)

Should be gray 20 I believe (you can see [Carbon v10 website](https://v10.carbondesignsystem.com/) for correct color)

Also in light theme, we should use white background for the left nav for contrast with the gray-10 content background.

```[tasklist]
### Tasks
- [ ] Update nav divider color in dark theme
- [ ] Re-add missing nav border
- [ ] Adjust margin (saw some extra margins — probably to accommodate the banner on the demo)
- [ ] Fix theme light mode nav theme colors
```

**Comment by elycheea** [comment]
@alisonjoseph We caught a few more style fixes when we implemented on our end. I can update this issue to include those as well and close carbon-design-system/carbon-for-products-website#101 in favor of this issue for tracking.
