### ISSUE TITLE
Website 10.3 Iteration plan

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#30]
# 10.3 Iteration Plan

This plan captures our work on the Website project for **May**. This work will consist of the content for the Patterns presentations for June, content updates to the Carbon website and the build-out of the IBM Design Language website and underlying Gatsby theme work in order to make that happen.

_Also included is providing assistance to /design/ai developers for their release and managing the build of the brand guidance site contractors to ensure adherence to our models and architecture._ 

## Patterns
@jeanservaas add issues here
- [ ] Curate already existing content
- [ ] Course outline with supporting materials to allow anyone to present the information 

 _1st or 2nd week of June, 2-day training_

## Content

This is work to continue to iterate and improve upon the content on the Carbon website. 

- [ ] Determine "core four" H2s https://github.com/carbon-design-system/carbon-website/issues/1599
- [ ] Establish page pattern w/ Sketch spec https://github.com/carbon-design-system/carbon-website/issues/1600
- [ ] Bring all existing content within new page pattern https://github.com/carbon-design-system/carbon-website/issues/1602
- [ ] Lead art on usage pages https://github.com/carbon-design-system/carbon-website/issues/1603
- [ ] Create and flesh out missing content https://github.com/carbon-design-system/carbon-website/issues/1604
- [ ] Replace variant images with contextual images https://github.com/carbon-design-system/carbon-website/issues/1605

## Carbon website

- [ ] Component status page design update https://github.com/carbon-design-system/carbon-website/issues/1486

## Re-architecture of the IBM Design Language website, and rebuild.

- [ ] Move IDL content to mdx https://github.com/carbon-design-system/design-language-website/issues/1 
- [ ] Icon library component https://github.com/carbon-design-system/carbon-website/issues/1485 https://github.com/carbon-design-system/carbon-website/issues/1325

## Development of Carbon's Gatsby website theme.
- [x] ResourceCard
- [x] ArticleCard #21 
- [x] ImageCard
- [x] Homepage #31
- [x] Prev/next #32
- [x] WebsiteTabs #14 
- [x] blockquote #18 
- [x] aside #19 
- [ ] navigation bugs #33
